config/routes.rb
Epistola::Application.routes.draw do

  resources :groups, :only => [:index, :show] do
    resources :messages, :only => [:index, :show] do
      member do
        get :permalink
      end
    end
  end
  
  match 'messages.json', :to => 'messages#create'
  
  match 'search' => 'searches#index'

  root :to => "groups#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :messages
  
  def conversations_count
    Message.conversations_count_in_group(self.id).
    all.first.count.to_i
  end
  
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :group, :counter_cache => true
  
  has_ancestry :orphan_strategy => :rootify
  validates_uniqueness_of :guid
  validates :group_id, :guid, :user, :presence => true
  
  # groupwise aggregate to get last post and message count per thread
  scope :threads, select("messages.id, messages.user, messages.subject, messages.created_at, 
  count(messages.thread_id) AS total").
                  joins("JOIN messages AS m2 ON messages.thread_id = m2.thread_id").
                  group("messages.thread_id, messages.id, messages.user, messages.subject, messages.created_at").
                  having("messages.created_at = MAX(m2.created_at)")
  scope :thread_starters, where("(in_reply_to = '' OR in_reply_to IS NULL) AND ancestry IS NULL")
  
  scope :conversations_count_in_group, lambda {|group_id| select("count(*)").joins("INNER JOIN (SELECT DISTINCT ON (thread_id) id FROM messages 
  WHERE messages.group_id = #{group_id} GROUP BY thread_id, id) AS m2 ON m2.id = messages.id")}
  
  # full text search with Postgres and texticle
  index do
    subject
    body
  end
  
  
  def last_message_in_thread
    if is_root? and is_childless?
      self
    elsif is_root? and has_children?
      descendants.last
    else
      root.descendants.last
    end
  end
  
  # gets a nested (ordered) hash that represents a message thread
  def get_thread
    is_root? ? subtree.arrange : root.subtree.arrange
  end
  
  # refers to number of authors in a thread
  def authors_count
    authors.keys.length
  end
  
  # groups a thread by authors
  def authors
    subtree.group_by {|m| m.user}    
  end
  
  def thread_title
    self.subject.gsub(/^[Re:\s]*/, '')
  end
  
  def author
    # gets rid of email address in name
    user.gsub(/\s*<[\w+\-.]+@[a-z\d\-.]+\.[a-z]+>/i, '')
  end
  
  def thread_param
    "#{id}-#{subject.strip.downcase.gsub('&', 'and').gsub(' ', '-').gsub(/[^\w-]/,'')}"
  end
  
  # full text search on subject and body, within a particular group or not
  def self.do_search(params, page)
    within_group = params[:group_id]
    if within_group
      search(params[:q]).where(:group_id => within_group).paginate(:page => page)
    else
      search(params[:q]).paginate(:page => page)
    end
  end
  
  # for tests - should probably be moved into a test helper
  def self.random_guid
    chars = (('a'..'z').to_a + ('0'..'9').to_a)
    (1..8).map { |a| chars[rand(chars.size)] }.join
  end
  
  # arrange newly downloaded messages into their inherent tree structure
  def self.arrange_into_tree
    if first_time?
      arrange_for_first_time
    else
      integrate_new_messages
    end
  end
  
  def self.arrange_for_first_time
    thread_starters.all.each do |msg|
      msg.update_attribute(:thread_id, next_thread_id) unless msg.thread_id
      msg.find_unassigned_children
    end
  end
  
  def self.integrate_new_messages
    where(:thread_id => nil).order("created_at asc").all.each do |msg|
      if msg.in_reply_to.blank?
        msg.update_attribute(:thread_id, next_thread_id)
      else
        p = where(:guid => msg.in_reply_to).first
        msg.assign_parent(p) if p
      end
    end
  end
  
  def find_unassigned_children
    if unassigned_children.any?
      unassigned_children.each do |child|
        child.assign_parent(self)
        child.find_unassigned_children
      end
    end
  end
  
  def assign_parent(some_parent)
    self.parent = some_parent
    self.thread_id = some_parent.thread_id
    self.save
  end
  
  def unassigned_children
    self.class.where(:in_reply_to => self.guid, :ancestry => nil).all
  end
  
  def self.next_thread_id
    highest_thread_id = maximum('thread_id')
    highest_thread_id ? (highest_thread_id + 1) : 1
  end
  
  def self.first_time?
    maximum('thread_id').nil?
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @conversations = @group.messages.threads.paginate(:page => params[:page])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]
  before_filter :authenticate_service, :only => [:create]
  
  def index
    @group = Group.find params[:group_id]
    # message will be the last in the thread
    @message = @group.messages.find(params[:thread]).root
    @messages = @message.subtree.paginate(:page => params[:page], :per_page => 20, 
                                          :order => "created_at ASC")
  end
  
  def show
    # permalink to message
    @message = Message.find(params[:id])
  end

  def create
    respond_to do |format|
      format.json do
        @group = Group.find_or_create_by_name(params[:message].delete(:group))
        @message = @group.messages.create(params[:message])
        render :json => @message.to_json        
      end
    end
  end

protected 
  
  def authenticate_service
    authenticate_or_request_with_http_basic do |id, password| 
      id == "andrea" && password == "secret"
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def index
    @query = params[:search][:q]
    if params[:commit] =~ /All/
      params[:search].delete(:group_id)
    else
      @group = Group.find(params[:search][:group_id]) if params[:search][:group_id]
    end
    @results = Message.do_search(params[:search], params[:page])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def excerpt_result(text, query)
    excerpted_text = excerpt(strip_tags(text), query)
    if excerpted_text.blank?
      truncate((strip_tags(text)), :length => 500)
    else
      highlight((excerpted_text), query)
    end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/groups/index.html.haml
- @groups.each do |group|
  .entries
    %p
      = link_to group.name, group_path(group) 
    %p
      = "#{pluralize(group.conversations_count, "conversation")} | #{pluralize(group.messages_count, "message")}"

app/views/groups/show.html.haml
%h2 
  = @group.name
  
#breadcrumbs 
  = link_to 'All Groups', groups_path
  >>
  = @group.name

.page-info.group
  .left
    = page_entries_info @conversations, :entry_name => 'conversation'
  .right
    = will_paginate @conversations

- @conversations.each do |conversation|
  .entries
    %p
      = link_to conversation.thread_title, group_messages_path(@group, :thread => conversation.thread_param)
    %p.group
      %span.left
        = #pluralize conversation.authors_count, "author"
        = pluralize conversation.total, "message"
      %span.right
        %strong
          Last Message: 
        = conversation.created_at.strftime("%b %d, %Y @ %H:%M")
        by
        = conversation.author

app/views/layouts/application.html.haml
!!! 5
%html
%head
  = csrf_meta_tag
  = stylesheet_link_tag 'compiled/screen', :media => 'screen'
  = stylesheet_link_tag 'compiled/print',  :media => 'print' 
  /[if lt IE 8]
    = stylesheet_link_tag 'compiled/ie'
  /[if lt IE 9]
    = javascript_include_tag 'html5'
%body
  #wrapper
    #wrapper-inner
      #header
        #logo
          = link_to image_tag("logo.jpg"), root_path
      #content.group
        #main
          = yield
        #aside
          %h2 Search         
          = form_tag search_path, :class => "bp search", :method => :get do
            %p
              = text_field_tag "search[q]", @query, :class => 'text'
            %p
              = submit_tag "All Groups", :class => "submit"
              - if @group
                = hidden_field_tag "search[group_id]", @group.id
                = submit_tag "This Group"
            
    = javascript_include_tag :defaults

app/views/messages/index.html.haml
#breadcrumbs 
  = link_to 'All Groups', groups_path
  >>
  = link_to @group.name, group_path(@group)
  >>
  = @message.subject

%h2.subject 
  = @message.subject
  %span
    = pluralize(@messages.length, "message")
.page-info.group
  .left
    = page_entries_info @messages, :entry_name => 'message'
  .right
    = will_paginate @messages 
- @messages.each do |message|
  .message
    %p.info.group
      %span.left
        = message.author
      %span.right
        = message.created_at.strftime("%b %d, %Y %H:%M")
    .body
      = simple_format(message.body)
        
.page-info.group
  .left
    = link_to "<< Back to Conversations", group_path(@group)
  .right
    = will_paginate @messages

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Conversation:
  = @message.conversation_id
%p
  %b User:
  = @message.user
%p
  %b Body:
  = @message.body

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

app/views/searches/index.html.haml
%h2.subject
  Search
  - if @group
    %span 
      = link_to @group.name, group_path(@group)

%h4 
  %strong
    = @results.total_entries
  result(s)
  found for
  %strong
    = @query
    
.page-info.group
  .left
    = page_entries_info @results, :entry_name => 'result'
  .right
    = will_paginate @results
    
- @results.each do |result|
  .message
    %h4
      = link_to excerpt_result(result.subject, @query), group_messages_path(result.group, result.thread_param)
    %p
      = excerpt_result(result.body, @query)
    .footer
      = result.created_at.strftime("%B %d")
      by
      = result.user

.page-info.group
  .left
    = page_entries_info @results, :entry_name => 'result'
  .right
    = will_paginate @results        